import = ["/Users/pradeep/.config/alacritty/themes/themes/github_dark.toml"]

[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[mouse]
hide_when_typing = true 

[window]
decorations = "Full"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.padding]
x = 5
y = 5
